### ISSUE TITLE
Use mysqli or PDO driver instead php-mysql

### ISSUE THREAD

**Issue by hr15a** [drakkr/QSOS#13]
[PHP Documentation](http://php.net/manual/en/mysqlinfo.api.choosing.php) points that the original MySQL driver is deprecated since PHP 5.5.0 release and will be removed on future versions.

O3S code should be upgraded to use MySQLi or PDO (preferably the last one as it is will allow switching to other DB engine easily)

**Comment by raphiki** [comment]
Thanks! We should like into this indeed.

**Comment by hr15a** [comment]
We're working on a fix with EDF

**Comment by raphiki** [comment]
@hr15a can we close tis issue?
