### ISSUE TITLE
qsos / mm format

### ISSUE THREAD

**Issue by gfgqsos** [drakkr/QSOS#16]
Hi,
Is there is a way to convert .qsos file in.mm one?
Thanks for your answer.

**Comment by hr15a** [comment]
Tools/o3s/formats/xml/xslt/eval-to-template.xsl can be used from command line using xsltproc to rebuild a MindMap template from existing evaluation.

This should also be used somewhere in o3s or during contribution process if an evaluation is submitted but not its template

**Comment by hr15a** [comment]
Mindmap generated with this XSL stylesheet is not totally XSD compliant : `xs:id attributes` generated by  XSL `generate-id` function are not valid and fails on XSD validation made by backend.

A workaround is to open the MM with freemind and save it before submitting to backend.

**Comment by raphiki** [comment]
_eval-to-template.xsl_ has been updated to work better.
Bear in mind that for now you still have to let _FreeMind_ convert the `.mm` generated file in the new format.
