### ISSUE TITLE
Blank Templates

### ISSUE THREAD

**Issue by 4thedocs** [drakkr/QSOS#17]
Hi, I would like to download a blank template, but I cannot find them on http://backend.qsos.org/index.php or in your repository. 
Thanks for your answer.

**Comment by t-moreau** [comment]
Hi,
blank templates (template_en.mm and template_fr.mm) can be found on
[https://github.com/drakkr/QSOS/tree/master/Tools/o3s/formats/xml/template](https://github.com/drakkr/QSOS/tree/master/Tools/o3s/formats/xml/template)

**Comment by 4thedocs** [comment]
thank you
