### ISSUE TITLE
O3S : synchro pda / OBM (O-Push + OBM-Sync) not found

### ISSUE THREAD

**Issue by t-moreau** [drakkr/QSOS#3]
in O3S (http://master.o3s.qsos.org/) in French:

The main page shows that there are only **2** available evaluations for "synchro pda".

But on the "synchro pda" page, **3** software are displayed.

If _OBM (O-Push + OBM-Sync)_ is selected, the visualization and the export functions don't work.

The _OBM (O-Push + OBM-Sync)_ evaluation seems to be missing. When you click on "xml", you get the message "/backend/master/OBM-(O-Push-+-OBM-Sync)-2.3.7_fr.qsos was not found on this server."

**Comment by raphiki** [comment]
o3s install guide has been updated
