### ISSUE TITLE
ODT & ODP export

### ISSUE THREAD

**Issue by DVanderstoken** [drakkr/QSOS#7]
Unable to export in ODT & ODP formats with errors creating png files

<pre>
Error 02: ODP generation PCLZIP_ERR_MISSING_FILE (-4) : File 'D:/DEV/servers/nginx-1.7.3/temp53ebf06bad8f9/tpl-ID_1783758993.png' does not exist
</pre>

**Comment by hr15a** [comment]
This works perfectly in a fresh install of o3s in Linux environment (tested recently on CentOS but should also work on Debian).

It looks like your installation has broken permission on temporary files so png files can't be created.
